### PR TITLE
Added sshd role so we can configure sshd.  From ansible-galaxy

### PR DESCRIPTION
**Pull request by mattrm**
Just adding the below to the hosts vars will stop root from logging in.

sshd_PermitRootLogin: no

### CODE REVIEW

**Comment by nigelbabu** [comment]
Can you add it to main.yml? I'd rather not have random roles lying around anymore.

Side note: Is it worth renaming to sshd? Going to be much easier to type with our own names rather that the source role name.

**Comment by nigelbabu** [comment]
I think it might also be a good idea to remove password access completely.

**Comment by mattrm** [comment]
It can be renamed, but we'll have to do that everytime we update the module.  That's not a massive issue.  Removing password access is fine, but that's not possible with this sshd module, I'll need to write something else to run passwd -d (which deletes the password).

**Comment by mattrm** [comment]
This has all been merged up after discussion with Nigel, so I'm closing this.

**Pull request merged**
